project:
  type: website
  render: 
    - "*.qmd"
    - "!ws23-24/zeitplan/"

website:
  title: "My Uni Notes"
  page-navigation: true
  navbar:
    left:
      - sidebar:semester
      - about.qmd

  sidebar:
    - id: semester
      title: "Semesters"
      style: "docked"
      contents:
        - section: "Bachelor"
          contents: 
            - ws23-24/index.qmd
            - ss24/index.qmd
            - ws24-25/index.qmd
            - ss25/index.qmd

    - title: "WS 23/24"
      style: "docked"
      contents:
        - ws23-24/ipi/ipi.qmd
        - ws23-24/num/num.qmd

    - title: "SS 24"
      contents:
        - ss24/alda/index.qmd
        - ss24/r/index.qmd
        - ss24/oop/index.qmd

    - title: "WS 24/25"
      contents:
        - ws24-25/isw/index.qmd
      
    - title: "SS 25"
      contents:
        - text: "alda"
          href: ss25/alda/index.qmd
        - text: "ibn"
          href: ss25/ibn/index.qmd
        - text: "scicomp"
          href: ss25/scicomp/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



