project:
  type: website
  render: 
    - "*.qmd"
    - "!ws23-24/zeitplan/"

website:
  title: "My Uni Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



