---
title: Week 8
date: 06/02/2025
---

## VL 15

### File Systems (cont.)

* inodes (cont.) 
* MBR (booting)
* FATx - MS-DOS
* UNIX-V7 
* structure of a hard disk
    * shortest seek time first (sstf)

#### RAID Systems

* RAID 0
* RAID 1 
    * mirroring
    * duplexing
* RAID 2 - bit-level striping, too complicated due to the need
  to synchronize hard disks 
* RAID 3 - XOR (reconstructing ), implementation is also very complex
* RAID 4
* RAID 5
* RAID 6 - like RAID 5 but wwith reed-solomon codes instead of XOR. 

## VL 16 - 04.06.25

* structure of file systems, block, blockgroups
* linux file systems: ext2, ext3, ext4, zfs. 

### Deadlocks 

* deadlocks, deadlock example  (p. 16)
* how to prevent deadlock: first we define a system model
* conditions for a resource deadlock
  * mutual exclusion: ...
  * hold and wait: ...
  * no preemption: ...
  * circular wait: ...
* this conditions must occur simultaneously for a deadlock to take place.
* resourcen-belegungs-graph (RB Graph)
  * multiple instances of a resource
* cycle detecting algorithms
  * recource vectors and resources rest vector
  * current allocation matrix 
  * request matrix 
* how to resolve deadlocks:

