---
title: Weekly Summary
---


## Week 1

### Lecture 1

**date**: 

### Lecture 2

**date**:

## Week 2

### Lecture 1

**date**: 22/4/24

* resources for R
  * advanced R ~ hadley wickham [link](https://adv-r.hadley.nz/)
  * r graphics cookbook [link](https://r-graphics.org/)
  * tidyverse
* packages 
    * installing and removing packages, package dependencies; shiny, learnr
    * namespaces and name collisions;
    * datasets package for learning; mtcars, iris
* function return value and print side effect
* clearing variables with `rm(x)`
* plotting
    * basic data plotting with `plot` 
    * basic function plotting with `plot` and `curve`

### Lecture 2

**date**: 26/4/24

* content: moodle videos 3 & 4
* r is object oriented - everything is an object
  * class vs typeof (small difference)
* r is also functional: everything that happens is a function call
  * difference between functions and function calls `sin` vs `sin()`
* atomic vectors vs lists 
* type casting 
* zero length vectors
* machine numbers (representation of real numbers in R)
* big integers - r represents large integers instead of 2's complement.
* vectors have no dimension, array has one dimension. vectors are **not** arrays.
* for data-sets use data-frames like: tibbles, data tables... 


## Week 3

### Lecture 1

**date**: 

### Lecture 2

**date**: 03/05/24 - Fri

* new features in R
  * other constructs instead of for loops that are faster
  * anonymous functions, lambda notation
  * discrete probability distributions
  * strings as factors
  * `.class2` can show all classes to which an object belongs, including implicit classes.
* new features in r 4.1
  * factor function behavior
  * native pipe operator, analogous to shell pipes, eliminating the need for magrittr pipes.
  * `as.vector()` removes attributes from a vector, like component names. 
  * colon operator precedence. 
  * tail recursion


## Week 1

### Lecture 1

**date**: 

### Lecture 2

**date**:

## Week 1

### Lecture 1

**date**: 

### Lecture 2

**date**:

## Week 1

### Lecture 1

**date**: 

### Lecture 2

**date**:

## Week 1

### Lecture 1

**date**: 

### Lecture 2

**date**:

## Week 1

### Lecture 1

**date**: 

### Lecture 2

**date**:

## Week 1

### Lecture 1

**date**: 

### Lecture 2

**date**:

## Week 1

### Lecture 1

**date**: 

### Lecture 2

**date**:

## Week 1

### Lecture 1

**date**: 

### Lecture 2

**date**:

## Week 1

### Lecture 1

**date**: 

### Lecture 2

**date**:

## Week 1

### Lecture 1

**date**: 

### Lecture 2

**date**:

## Week 1

### Lecture 1

**date**: 

### Lecture 2

**date**:

## Week 1

### Lecture 1

**date**: 

### Lecture 2

**date**:









