## Week 1

### Lecture 1

* **date**: 15/10/24
* Intro
    * LOC = lines of code. 
    * Development time - quality
    * SWE at-large vs at-small
    * Activities and design decisions
* organisatory: moodle pass isw2425
* [acrasia](https://www.wikiwand.com/en/articles/Akrasia)

### Lecture 2 (tech)

* **date**:  15/10/24
* organisatory infos
* java overview

### Tutorial (L. Moritz)

* **date**: 16/10/24
* 

## Week 2

### Lecture 1

* **date**: 22/10/24
* Process & Project 
* Team organisation
* Extreme programming 
* software development tools like git
* requirements engineering
* GenAI (Uni Heidelberg => Yoki)

### Lecture 2 (tech)

* **date**: 22/10/24
* java review 2:
  * Inheritence
  * Object construction and types casts
  * parameter passing: primitive types as value, objects as reference
* git review:
* chatGPT overview


## Week 3

### Lecture 1

* **date**: 29/10/24
* Requirements Engineering
  * Usage/User Description
  * Task and FuncArrayListtion Description
  * GUI Description

### Lecture 2 (tech)

* **date**: 29/10/24
* git 
* issue tracking
* android basics


### Tutorium

* Questions:
* A.3.1:
  * how exactly combat score?
    * 
* A.3.2:
  * Arbeitsbereich?
  * UI-Struktur-Diagramm? 
  * konkrete Sicht / virtual Windows ? 
  * excel datei selbst erstellen oder ist sie auf confluence? 
* A.3.3:
  * is `MainActivity` a UI class or a data class?
  * What are 
    * `RecyclerView` ? 
    * `Adapter` ?
    * `ViewHolder` ?
    * `import de.uhd.ifi.pokemonmanager.R` ?
  * **Layout Ressourcen** fuer `MainActivity` und `RecyclerView`?  

## Week 4

### Lecture 1

* **date**: 05/11/24
* ui-design principles
* usability


### Lecture 2 (tech)

* **date**: 05/11/24
* some advanced java stuff

## Week 5

### Lecture 1

* **date**: 

### Lecture 2

* **date**: 

## Week 6

### Lecture 1

* **date**: 

### Lecture 2

* **date**: 

## Week 7

### Lecture 1

* **date**: 

### Lecture 2

* **date**: 

## Week 8

### Lecture 1

* **date**: 

### Lecture 2

* **date**: 

## Week 9

### Lecture 1

* **date**: 

### Lecture 2

* **date**: 

## Week 10

### Lecture 1

* **date**: 

### Lecture 2

* **date**: 

## Week 11

### Lecture 1

* **date**: 

### Lecture 2

* **date**: 

## Week 12

### Lecture 1

* **date**: 

### Lecture 2

* **date**: 

## Week 13

### Lecture 1

* **date**: 

### Lecture 2

* **date**: 

## Week 14

### Lecture 1

* **date**: 

### Lecture 2

* **date**: 

## Week 15

### Lecture 1

* **date**: 

### Lecture 2

* **date**: 

